### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by alex-v1981** [pybee/Python-iOS-support#7]
checking for uintptr_t... yes
checking size of uintptr_t... configure: error: in `/Volumes/DATA/Work/macsoftex/Projects/Python-iOS-support/build/Python-2.7.1/ios-simulator':
configure: error: cannot compute sizeof (uintptr_t)
See `config.log' for more details.
make: *** [build/python/ios-simulator/Python] Error 77

**Comment by freakboy3742** [comment]
I can't think of any reason that the Python configure step would fail unless there is something odd in your developer tools configuration.

Can you provide any details about your setup - versions of OS/X, Xcode etc?

**Comment by alex-v1981** [comment]
OS X 10.10.3
XCode 6.3.1

**Comment by 4ntoine** [comment]
i'm having this issue too. any update on it?

**Comment by freakboy3742** [comment]
I'm not doing much work on the 2.7 branch, so no - I don't have any updates. I'm not sure what would be causing it - can you provide any details about your build environment? When in the build process does this error manifest?

**Comment by 4ntoine** [comment]
http://stackoverflow.com/questions/35099885/build-python-2-7-1-for-ios-error-type-name-cannot-be-signed-or-unsigned

**Comment by 4ntoine** [comment]
Seems so strange..

**Comment by 4ntoine** [comment]
BTW [kivy-ios](https://github.com/kivy/kivy-ios) build failed with exactly the same error:

```
./toolchain build python
...
checking size of uintptr_t... configure: error: in `/Users/asmirnov/Documents/dev/src/kivy-ios3/build/python/i386/Python-2.7.1':
configure: error: cannot compute sizeof (uintptr_t)
See `config.log' for more details.
Traceback (most recent call last):
  File "./toolchain.py", line 1227, in <module>
    ToolchainCL()
  File "./toolchain.py", line 1043, in __init__
    getattr(self, args.command)()
  File "./toolchain.py", line 1067, in build
    build_recipes(args.recipe, ctx)
  File "./toolchain.py", line 936, in build_recipes
    recipe.execute()
  File "/Users/asmirnov/Documents/dev/src/kivy-ios3/toolchain.py", line 559, in execute
    self.build_all()
  File "/Users/asmirnov/Documents/dev/src/kivy-ios3/toolchain.py", line 56, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/asmirnov/Documents/dev/src/kivy-ios3/toolchain.py", line 646, in build_all
    self.build(arch)
  File "/Users/asmirnov/Documents/dev/src/kivy-ios3/toolchain.py", line 56, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/asmirnov/Documents/dev/src/kivy-ios3/toolchain.py", line 633, in build
    self.build_arch(arch)
  File "/Users/asmirnov/Documents/dev/src/kivy-ios3/recipes/python/__init__.py", line 53, in build_arch
    _env=build_env)
  File "/Users/asmirnov/Documents/dev/src/kivy-ios3/toolchain.py", line 39, in shprint
    for line in command(*args, **kwargs):
  File "./tools/external/sh.py", line 565, in next
    self.wait()
  File "./tools/external/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "./tools/external/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_77: 
```

**Comment by freakboy3742** [comment]
That's not entirely surprising - the Python 2.7 toolchain draws heavily on Kivy's starting point.

I'd be *very* interested to hear if you get the same problem with the Python 3.4 branch.

**Comment by 4ntoine** [comment]
Unfortunately I need only 2.7
30 Янв 2016 г. 19:24 пользователь "Russell Keith-Magee" <
notifications@github.com> написал:

**Comment by 4ntoine** [comment]
i can confirm it CAN be built with Xcode 6.4 and CAN'T be BUILT with Xcode 7.2 using this tutorial: https://github.com/D-Cipher/My-Courses/blob/master/Various%20Guides/Kivy%20IOS%20Build%20Guide%20for%20Xcode%206.4.md
